#server.port: 9966
#spring.profiles: default

#management.security.enabled: false

#spring.jpa.hibernate.ddl-auto: validate

spring:
  profiles:
    active: development
datasource:
  url: "jdbc:h2:mem:test"
  driverClassName: org.h2.Driver
  username: sa
password: ""
  #data: "classpath*:data.sql"
spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect

#management.security.enabled: false

#security:
#  basic:
#    enabled: false
management:
  security:
    enabled: false

spring.jpa.hibernate.ddl-auto: validate

spring.h2.console.enabled: true

query.user: select email, password, active from user where email=?






