/*
CREATE TABLE PERSON (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	last_name varchar(255) not null
);

insert into PERSON (first_name, last_name) values ('Dave', 'Syer');
insert into PERSON (first_name, last_name) values ('Jarek', 'Zyzak');
insert into PERSON (first_name, last_name) values ('Abcd', 'Zzzz');
insert into PERSON (first_name, last_name) values ('CCCC', 'Ghsa');
*/
CREATE TABLE USER (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  active INTEGER NOT NULL,
  email varchar(255) not null,
  last_name varchar(255) not null,
  first_name varchar(255) not null,
  username varchar(255) not null,
  password varchar(255) not null
);

CREATE TABLE ROLE (
  role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role VARCHAR(255) NOT NULL
);
--book_publisher
CREATE TABLE USER_ROLE(
  user_id INTEGER NOT NULL,
  role_id INTEGER NOT NULL,
  PRIMARY KEY(user_id, role_id),
  CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES USER(user_id),
  CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES ROLE(role_id)
);

INSERT INTO USER(active,email,last_name,first_name,username,password) VALUES (1,'jarekpc@o2.pl','Zyzak','Jarek','jazy', 'poke123');

INSERT INTO ROLE(role)
VALUES('ADMIN');

INSERT INTO USER_ROLE(user_id, role_id) VALUES (1,1);
