CREATE TABLE PERSON (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	last_name varchar(255) not null
);

insert into PERSON (first_name, last_name) values ('Dave', 'Syer');
insert into PERSON (first_name, last_name) values ('Jarek', 'Zyzak');
insert into PERSON (first_name, last_name) values ('Abcd', 'Zzzz');

CREATE TABLE ROLE (
  role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role varchar(255) not null
);

CREATE TABLE USER (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  active INTEGER NOT NULL,
  email varchar(255) not null,
  last_name varchar(255) not null,
  first_name varchar(255) not null,
  username varchar(255) not null,
  password varchar(255) not null
);

CREATE TABLE USER_ROLE (
  user_id INTEGER NOT NULL,
  role_id INTEGER NOT NULL
);

ALTER TABLE USER_ROLE ADD PRIMARY KEY (user_id, role_id);
ALTER TABLE USER_ROLE ADD FOREIGN KEY (user_id) REFERENCES USER(user_id);
ALTER TABLE USER_ROLE ADD FOREIGN KEY (role_id) REFERENCES ROLE(role_id);

INSERT INTO ROLE(role) VALUES ('ADMIN');

INSERT INTO USER(active,email,last_name,first_name,username,password) VALUES (1,'jarekpc@o2.pl','Zyzak','Jarek','jazy', 'poke');

